### ISSUE TITLE
Issue in screenshot of DataAnalytics Lab4 tan file.

### ISSUE THREAD

**Issue by TopRamen1** [KAIR-ISZ/public_lectures#14]
File: https://github.com/KAIR-ISZ/public_lectures/blob/master/Data%20Analytics%202022/Lab%204%20-%20Linear%20models/height_2a_ppc.png

File contains issue in line 12 in for loop.
height and weight should go over i variable not N.

**Comment by jerzybaranowski** [comment]
@adudekagh could you please correct the screenshot?
